@hostUrlLocal = http://localhost:7071/api/
@hostUrlAzure = https://ga-serverlessapidemo-cc-fa.azurewebsites.net/api/
@hostUrlApim = https://ga-serverlessapidemo-cc-apim.azure-api.net/serverlesstodo
@hostUrl = {{hostUrlApim}}
@subscriotionKey = 677b18fddf2844a99c52d2c9837efac1

### Welcome
GET {{hostUrl}}/Welcome
#subscription-key: {{subscriotionKey}} 


### HealthCheck
HEAD {{hostUrl}}/todos
#subscription-key: {{subscriotionKey}} 


### GetAllTodos
GET {{hostUrl}}/todos
#subscription-key: {{subscriotionKey}} 


### GetTodo
GET {{hostUrl}}/todos/1
#subscription-key: {{subscriotionKey}} 


### CreateTodo
POST {{hostUrl}}/todos
Content-Type: application/json
#subscription-key: {{subscriotionKey}} 

{
  "name": "test4",
  "description": "",
  "completed": false,
  "completedDateUtc": null,
  "id": "4",
  "type": "todo",
  "createdDateUtc": "2022-05-04T18:41:21.5094333+00:00",
  "ttl": -1
}


### UpdateTodo
PUT {{hostUrl}}/todos/1
Content-Type: application/json
#subscription-key: {{subscriotionKey}} 

{
  "name": "test1",
  "description": "updated 2",
  "completed": false,
  "completedDateUtc": null,
  "id": "1",
  "type": "todo",
  "createdDateUtc": "2022-05-04T18:41:21.5094333+00:00",
  "ttl": -1
}


### DeleteTodo
DELETE {{hostUrl}}/todos/3
#subscription-key: {{subscriotionKey}} 
